# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- task: SqlAzureDacpacDeployment@1
  inputs:
    AuthenticationType: 'server'
    ServerName: 'localhost,5432'
    DatabaseName: 'blockchain_test'
    SqlUsername: 'postgres'
    SqlPassword: 'postgres'
    deployType: 'SqlTask'
    SqlFile: '\\TP\backend\blockchaintest.sql'
    IpDetectionMethod: 'AutoDetect'
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
