
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop
- task: SqlAzureDacpacDeployment@1
  inputs:
    AuthenticationType: 'server'
    ServerName: 'localhost,5432'
    DatabaseName: 'blockchain_test'
    SqlUsername: 'postgres'
    SqlPassword: 'postgres'
    deployType: 'SqlTask'
    SqlFile: '\\TP\backend\blockchaintest.sql'
    IpDetectionMethod: 'AutoDetect'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    createdb -h localhost -p 5432 -U postgres -E utf8 blockchain
    cd backend
    psql -d blockchain -U postgres -f blockchainexport.sql
    npm install
    npm test
  displayName: 'Install backend and test'



