version: '3.3'
services:
  db:
    image: postgres:10
    restart: always
    environment: 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: blockchain
    expose:
        - 5432
  backend:
    image: blockpay.azurecr.io/nodejs-backend:latest
    build:
        context: ./backend
        dockerfile: Dockerfile
    expose:
        - 8080
    environment:
        APP_SERVER_PORT: 8080
    depends_on: 
        - db
    links:
        - db
  frontend:
    image: blockpay.azurecr.io/angularjs-frontend:latest
    build:
        context: ./frontend
        dockerfile: Dockerfile
        args:
            env: prod
    environment: 
        APP_CLIENT_PORT: 4200
    ports:
        - "4200:4200"
    links:
        - backend