version: '3'

services:

#Setup database container  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: blockchain
    ports:
      - "5432:5432"

#Setup node container
  server:
    build: ./backend
    expose:
      - 8080
    environment:
      API_HOST: "http//localhost:3000"
      APP_SERVER_PORT: 8080
    depends_on:
      - db

#Setup client container
  client:
    build: ./frontend
    environment:
      - APP_CLIENT_PORT=4200
    expose:
      - 4200
    links:
      - server